# Generated by Django 5.1.6 on 2025-02-19 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='product',
            old_name='size',
            new_name='file_size',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='images',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pages_count',
            new_name='pages',
        ),
        migrations.RenameField(
            model_name='salesman',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='salesman',
            old_name='total_sell_product',
            new_name='sold_products_count',
        ),
        migrations.RenameField(
            model_name='salesman',
            old_name='income',
            new_name='total_income',
        ),
        migrations.RemoveField(
            model_name='product',
            name='author',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='childrens', to='app.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='file',
            field=models.FileField(null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='file_type',
            field=models.CharField(choices=[('docs', '.docs'), ('pptx', '.pptx'), ('pdf', '.pdf')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='poster',
            field=models.ImageField(null=True, upload_to='product_poster/'),
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.salesman'),
        ),
        migrations.AddField(
            model_name='product',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesman',
            name='backgroud_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/Seller_backgroud_image'),
        ),
        migrations.AddField(
            model_name='salesman',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='seller_image'),
        ),
        migrations.AddField(
            model_name='salesman',
            name='last_active',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='app.tag'),
        ),
    ]
